### ISSUE TITLE
Où retrouver la source de données?

### ISSUE THREAD

**Issue by gausoft** [smirltech/open-kongo#5]
J'imagine que les data actuelles proviennent de votre base de données!?

**Comment by MarienMupenda** [comment]
Ce projet est une amélioration, d'un projet existant qui était réservé à l'utilisation interne.
Les données étaient en excel puis importées dans MySQL.
Mais il y'a moyen d'ajouter le fichier datasource.sql au projet pour faciliter la contribution.

**Comment by yveskalume** [comment]
Pourquoi pas sous format JSON ?

**Comment by gausoft** [comment]
Yes, justement pour faciliter la portabilité des données

**Comment by MarienMupenda** [comment]
Je viens d'ajoutes les fichiers de données (json et sql).
Merci pour votre contribution. @YvesKalume et @gausoft
